let actionTypes = {
    APIINFO_FETCH_SUCCESS: 'APIINFO_FETCH_SUCCESS',

    REGISTRATION_SUBMISSION_SUCCESS: 'REGISTRATION_SUBMISSION_SUCCESS',
    REGISTRATION_SUBMISSION_ERROR: 'REGISTRATION_SUBMISSION_ERROR',
};

export default actionTypes;
